# Generated by Django 6.1 on 2026-09-16 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_project_project_image_url_project_tech_stack_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_image_url',
            new_name='thumbnail',
        ),
    ]
