# Generated by Django 6.1 on 2026-09-28 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_project_starred_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='starred_by',
            new_name='stars',
        ),
    ]
